### ISSUE TITLE
missing file 'datas/statistics.csv'

### ISSUE THREAD

**Issue by ThomasW2005** [fabian57fabian/archero_bot_57#22]
I tried the bot with Nox and my Android phone (Xiaomi A1), but i get the same error everytime. When i start GameController.py, while having Nox opened or my phone connected, this is what is printed in the Console:

```
 Errors writing statistics: [Errno 2] No such file or directory: 'datas/statistics.csv'
QPixmap::scaled: Pixmap is a null pixmap
adb server version (36) doesn't match this client (41); killing...
* daemon started successfully
disconnected everything
error: protocol fault (couldn't read status length): connection reset
adb server version (36) doesn't match this client (41); killing...
* daemon started successfully
disconnected everything
connected to 127.0.0.1:62001
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\thoma\Downloads\archero_bot_57-master\archero_bot_57-master\WorkerThread.py", line 15, in run
    self.function()
  File "C:\Users\thoma\Downloads\archero_bot_57-master\archero_bot_57-master\UsbConnector.py", line 267, in _oneCheck
    c = self.tryConnect()
  File "C:\Users\thoma\Downloads\archero_bot_57-master\archero_bot_57-master\UsbConnector.py", line 91, in tryConnect
    self._changeConnectedState(True)
  File "C:\Users\thoma\Downloads\archero_bot_57-master\archero_bot_57-master\UsbConnector.py", line 35, in _changeConnectedState
    f()
  File "C:\Users\thoma\Downloads\archero_bot_57-master\archero_bot_57-master\CaveDungeonEngine.py", line 129, in onConnectionStateChanged
    self.initDataFolders()
  File "C:\Users\thoma\Downloads\archero_bot_57-master\archero_bot_57-master\CaveDungeonEngine.py", line 109, in initDataFolders
    self.dataFolders = readAllSizesFolders()
  File "C:\Users\thoma\Downloads\archero_bot_57-master\archero_bot_57-master\Utils.py", line 39, in readAllSizesFolders
    folders = [f for f in os.listdir("datas") if os.path.isdir(os.path.join("datas", f))]
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'datas'
```

**Hardware description**
 - Smartphone: Xiaomi A1 / Nox
 - Screen size: 1920x1080
 - Computer OS: Windows 10 Pro 20H2 Build 1904.867

**Screenshots**
![image](https://user-images.githubusercontent.com/63959563/112764444-d1448980-9008-11eb-962f-8ce6229c56db.png)

**Additional context**

**Comment by ThomasW2005** [comment]
![image](https://user-images.githubusercontent.com/63959563/112764485-0d77ea00-9009-11eb-831e-aaa85fc45b33.png)
The file also isn't there

**Comment by fabian57fabian** [comment]
Hi @ThomasW2005 the bot works as following:

When a smartphone is connected, he takes the resolution info and goes into the corresponding folder (WIDTHxHEIGHT) in **datas** folder.

If you have a **different resolution** than the ones you see in datas folder, you can't play the bot.

e.g. having w=1080, h=2230 as phone resolution, there isn't a _datas/1080x2230_ folder containing necessary datas, so it will output an error.

Reporting a corresponding error will be soon fixed, but in the meantime i suggest you to play using Nox player and setting 1080x1920 resolution as showed in the youtube installation [video](https://youtu.be/TDmbmIrT5Vc).

**Comment by fabian57fabian** [comment]
Btw, it seems like datas folder does not exist at all from the console log.

Could you please copy the entire console output? Thanks
