### ISSUE TITLE
GameController and TouchManager will no launch and do not open

### ISSUE THREAD

**Issue by AdminZero** [fabian57fabian/archero_bot_57#27]
Hello, is this something broken in the script or something I installed wrong?  

 File "C:\archero_bot_57-master\update_manager.py", line 1, in <module>
    from requests import get
ModuleNotFoundError: No module named 'requests'

GameController and TouchManager don't launch and get an error...

C:\archero_bot_57-master>GameController.py
Traceback (most recent call last):
  File "C:\archero_bot_57-master\GameController.py", line 2, in <module>
    from GameController.GameControllerView import GameControllerWindow
  File "C:\archero_bot_57-master\GameController\GameControllerView.py", line 4, in <module>
    from GameController.GameControllerModel import GameControllerModel, EngineState
  File "C:\archero_bot_57-master\GameController\GameControllerModel.py", line 8, in <module>
    from update_manager import UpdatesManager
  File "C:\archero_bot_57-master\update_manager.py", line 1, in <module>
    from requests import get
ModuleNotFoundError: No module named 'requests'

C:\archero_bot_57-master>TouchManager.py
Traceback (most recent call last):
  File "C:\archero_bot_57-master\TouchManager.py", line 2, in <module>
    from TouchManager.TouchManagerView import TouchManagerWindow
  File "C:\archero_bot_57-master\TouchManager\TouchManagerView.py", line 9, in <module>
    from TouchManager.CoordinatesSelector import CoordinatesSelector
  File "C:\archero_bot_57-master\TouchManager\CoordinatesSelector.py", line 9, in <module>
    from QMyWidgets.QLevelState import QLevelState, PlayState
  File "C:\archero_bot_57-master\QMyWidgets\QLevelState.py", line 15, in <module>
    from GameController.GameControllerModel import GameControllerModel
  File "C:\archero_bot_57-master\GameController\GameControllerModel.py", line 8, in <module>
    from update_manager import UpdatesManager
  File "C:\archero_bot_57-master\update_manager.py", line 1, in <module>
    from requests import get
ModuleNotFoundError: No module named 'requests'

The StaticCoords is the only one that seems to work (kind of)...

C:\archero_bot_57-master>check_static_coords.py
0: 1080x1920
Select your number0
Using datas\1080x1920\screens
Do you wish to debug? (set yes only if you did it already once and found some rows with NO_DETECTION): (y/n):n
NO_DETECTION - announcement_homescreen.png   + door_is_open
NO_DETECTION - hatchery.png
MUL_DETECTIONS hero_patrol.png: btn_home_time_reward, popup_home_patrol
OK - hero_patrol_not_available.png: btn_home_time_reward
NO_DETECTION - hero_patrol_rewarded.png
OK - menu_equipment.png: menu_equip  + least_5_energy
OK - menu_events.png: menu_events  + least_5_energy
OK - menu_pause.png: on_pause
OK - menu_shop.png: menu_shop  + least_5_energy
OK - menu_shop_heromode.png: menu_shop  + least_5_energy
OK - menu_start_pressed.png: start_with_raid
OK - menu_talent.png: menu_talents  + least_5_energy
OK - menu_talent_altar.png: menu_talents  + least_5_energy
OK - menu_talent_rune.png: menu_talents  + least_5_energy
NO_DETECTION - menu_wind_achivements.png
NO_DETECTION - menu_wind_clan.png
NO_DETECTION - menu_wind_daily_quests.png
NO_DETECTION - menu_wind_login_gifts.png
NO_DETECTION - menu_wind_user.png
NO_DETECTION - menu_wind_weekly_quests.png   + door_is_open
OK - menu_world.png: menu_home  + least_5_energy
NO_DETECTION - monster_book.png
NO_DETECTION - monster_farm.png
OK - play_center_door.png: in_game   + door_is_open
OK - play_doorclosed.png: in_game
OK - play_endgame.png: endgame. Extra detected singulars: equip_question_ask
OK - play_ingame.png: in_game
OK - play_level_after_door.png: in_game
OK - play_lucky_wheel.png: fortune_wheel
OK - play_lucky_wheel_powerup.png: fortune_wheel
OK - play_max_level.png: in_game   + door_is_open
OK - play_met_devil.png: devil_question
OK - play_misterious_vendor.png: mistery_vendor  + least_5_energy
OK - play_misterious_vendor_ad.png: mistery_vendor  + least_5_energy
OK - play_select_ability.png: select_ability
OK - play_select_ability2.png: select_ability
OK - play_special_reward.png: special_gift_respin  + least_5_energy
OK - play_stating_ability.png: select_ability
OK - play_you_found_angel.png: angel_heal
OK - play_you_met_master.png: ad_ask
NO_DETECTION - rewards_welcome_back.png
Got some failed tests. It is advised not to use the bot. Infinite loops and damage can be done by randomly clicking without knowledge.

**Comment by AdminZero** [comment]
Python 3.10.4 seems to give that error... I rolled back my python to 3.9.13 and the touch manager works now.  I did not test any other versions of python besides those two.  I will be using python 3.9.13 now until otherwise noted.
