### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by Areu888** [fabian57fabian/archero_bot_57#37]
I followed all 3 videos and it still doesn't work
Device doesn't connect on emulator, I keep getting this error:
>>>>>>>> ########################## <<<<<<<<
Updates checked. All right.
failed to connect to 127.0.0.1:5037
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\addse\Downloads\archero_bot_57-master\archero_bot_57-master\WorkerThread.py", line 15, in run
    self.function()
  File "C:\Users\addse\Downloads\archero_bot_57-master\archero_bot_57-master\UsbConnector.py", line 271, in _oneCheck
    c = self.tryConnect()
  File "C:\Users\addse\Downloads\archero_bot_57-master\archero_bot_57-master\UsbConnector.py", line 91, in tryConnect
    self._changeConnectedState(True)
  File "C:\Users\addse\Downloads\archero_bot_57-master\archero_bot_57-master\UsbConnector.py", line 35, in _changeConnectedState
    f(self.connected)
  File "C:\Users\addse\Downloads\archero_bot_57-master\archero_bot_57-master\CaveDungeonEngine.py", line 225, in onConnectionStateChanged
    self.updateScreenSizeByPhone()
  File "C:\Users\addse\Downloads\archero_bot_57-master\archero_bot_57-master\CaveDungeonEngine.py", line 233, in updateScreenSizeByPhone
    self.screen_connector.changeScreenSize(w, h)
  File "C:\Users\addse\Downloads\archero_bot_57-master\archero_bot_57-master\GameScreenConnector.py", line 69, in changeScreenSize
    self.specific_checks_coords = loadJsonData(self.specific_checks_path)
  File "C:\Users\addse\Downloads\archero_bot_57-master\archero_bot_57-master\Utils.py", line 7, in loadJsonData
    with open(path, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'datas\\1080x2340\\coords\\static_specific_coords.json'

I also tried to run "check_static_coords" and doesn't work as well

**Comment by fabian57fabian** [comment]
Hello @Areu888 ,
Given the output calling a file in 'datas\1080x2340\coords\static_specific_coords.json' path,
it seems that the bot is trying to connect to a device having screen size 1080x2340 wich is a resolution not supported.
The only one supported is 1080x1920.
Are you sure that the emulator you are using have this resolution?

**Comment by Areu888** [comment]
Yes, I selected the same settings as the video, not sure why it's showing 2340

**Comment by Areu888** [comment]
I unplugged my phone and it detected Nox now, it's working, thanks

**Comment by fabian57fabian** [comment]
Could you take a screenshot from the emulator and verify the screen size?
Please also update the archero bot and the emulator.

**Comment by fabian57fabian** [comment]
Closing because no answer provided
