### ISSUE TITLE
Exception Folder doesn't Exist

### ISSUE THREAD

**Issue by Herya** [fabian57fabian/archero_bot_57#48]
**Hardware description**
 - Nox
 - Screen size: [e.g. 1080x1920]
 - Computer OS: [Windows 10]

Since today it's looking for a folder that doesn't exist. If I create the folder from the other on by copying, it doesn't work.
I tried downloading from here again and replace the files but it didn't work

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Software Download\archero_bot_57-master\src\WorkerThread.py", line 15, in run
    self.function()
  File "D:\Software Download\archero_bot_57-master\src\UsbConnector.py", line 276, in _oneCheck
    c = self.tryConnect()
  File "D:\Software Download\archero_bot_57-master\src\UsbConnector.py", line 96, in tryConnect
    self._changeConnectedState(True)
  File "D:\Software Download\archero_bot_57-master\src\UsbConnector.py", line 40, in _changeConnectedState
    f(self.connected)
  File "D:\Software Download\archero_bot_57-master\src\CaveDungeonEngine.py", line 177, in onConnectionStateChanged
    self.updateScreenSizeByPhone()
  File "D:\Software Download\archero_bot_57-master\src\CaveDungeonEngine.py", line 185, in updateScreenSizeByPhone
    self.screen_connector.changeScreenSize(w, h)
  File "D:\Software Download\archero_bot_57-master\src\GameScreenConnector.py", line 73, in changeScreenSize
    self.specific_checks_coords = loadJsonData(self.specific_checks_path)
  File "D:\Software Download\archero_bot_57-master\src\Utils.py", line 18, in loadJsonData
    with open(path, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Software Download\\archero_bot_57-master\\datas\\1080x2340\\coords\\static_specific_coords.json'`

**Comment by fabian57fabian** [comment]
Hello, sorry for the late reply.
As for latest 2 or 3 versions, the Archero Bot only works with screen size 1080x1920 (e.g. old phones or emulators).
You either have a connected phone or didn't change the screen resolution on emulator  to 1080 x 1920.

As i can see you're using **1080x2340**.

But since this isn't the first time, i'll add a warning when this happends for future misunderstandings.
Thank you for telling us.

**Comment by Herya** [comment]
Nox was set to the correct resolution cause I always use that one.
Yes it was probably my phone connected in USB, didnt know you couldn't have a phone connected while using it ;)
